// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_topics.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addFeedTopic = `-- name: AddFeedTopic :exec
INSERT INTO feed_topics (
    id,
    created_at,
    updated_at,
    feed_id,
    topic_id
) VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
`

type AddFeedTopicParams struct {
	ID      uuid.UUID
	FeedID  uuid.UUID
	TopicID uuid.UUID
}

func (q *Queries) AddFeedTopic(ctx context.Context, arg AddFeedTopicParams) error {
	_, err := q.db.ExecContext(ctx, addFeedTopic, arg.ID, arg.FeedID, arg.TopicID)
	return err
}
