// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addFeed = `-- name: AddFeed :one
INSERT INTO feeds (
    id, 
    created_at, 
    updated_at, 
    title, 
    descrip, 
    link,
    feed_link, 
    updated_parsed,
    published_parsed, 
    lang, 
    img_url, 
    img_title, 
    feed_type, 
    user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, created_at, updated_at, title, descrip, link, feed_link, updated_parsed, published_parsed, lang, img_url, img_title, feed_type, user_id, last_fetched_at
`

type AddFeedParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Descrip         string
	Link            string
	FeedLink        string
	UpdatedParsed   sql.NullTime
	PublishedParsed sql.NullTime
	Lang            string
	ImgUrl          string
	ImgTitle        string
	FeedType        string
	UserID          uuid.UUID
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, addFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Descrip,
		arg.Link,
		arg.FeedLink,
		arg.UpdatedParsed,
		arg.PublishedParsed,
		arg.Lang,
		arg.ImgUrl,
		arg.ImgTitle,
		arg.FeedType,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Descrip,
		&i.Link,
		&i.FeedLink,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Lang,
		&i.ImgUrl,
		&i.ImgTitle,
		&i.FeedType,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, created_at, updated_at, title, descrip, link, feed_link, updated_parsed, published_parsed, lang, img_url, img_title, feed_type, user_id, last_fetched_at FROM feeds
WHERE id = $1
`

func (q *Queries) GetFeedByID(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Descrip,
		&i.Link,
		&i.FeedLink,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Lang,
		&i.ImgUrl,
		&i.ImgTitle,
		&i.FeedType,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeedsByTopicID = `-- name: GetFeedsByTopicID :many
SELECT DISTINCT feeds.id, feeds.created_at, feeds.updated_at, feeds.title, feeds.descrip, feeds.link, feeds.feed_link, feeds.updated_parsed, feeds.published_parsed, feeds.lang, feeds.img_url, feeds.img_title, feeds.feed_type, feeds.user_id, feeds.last_fetched_at, COUNT(feed_follows.user_id) AS follower_count
FROM feeds
JOIN feed_topics ON feeds.id = feed_topics.feed_id
LEFT JOIN feed_follows ON feeds.id = feed_follows.feed_id
WHERE feed_topics.topic_id = ANY($1::UUID[])
  AND (feeds.lang = $2 OR $2 = '')
  AND (feeds.feed_type = $3 OR $3 = '')
GROUP BY feeds.id
ORDER BY follower_count DESC, feeds.created_at DESC
OFFSET $4
LIMIT $5
`

type GetFeedsByTopicIDParams struct {
	Column1  []uuid.UUID
	Lang     string
	FeedType string
	Offset   int32
	Limit    int32
}

type GetFeedsByTopicIDRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Descrip         string
	Link            string
	FeedLink        string
	UpdatedParsed   sql.NullTime
	PublishedParsed sql.NullTime
	Lang            string
	ImgUrl          string
	ImgTitle        string
	FeedType        string
	UserID          uuid.UUID
	LastFetchedAt   sql.NullTime
	FollowerCount   int64
}

func (q *Queries) GetFeedsByTopicID(ctx context.Context, arg GetFeedsByTopicIDParams) ([]GetFeedsByTopicIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByTopicID,
		pq.Array(arg.Column1),
		arg.Lang,
		arg.FeedType,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsByTopicIDRow
	for rows.Next() {
		var i GetFeedsByTopicIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Descrip,
			&i.Link,
			&i.FeedLink,
			&i.UpdatedParsed,
			&i.PublishedParsed,
			&i.Lang,
			&i.ImgUrl,
			&i.ImgTitle,
			&i.FeedType,
			&i.UserID,
			&i.LastFetchedAt,
			&i.FollowerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsToFetch = `-- name: GetFeedsToFetch :many
SELECT id, created_at, updated_at, title, descrip, link, feed_link, updated_parsed, published_parsed, lang, img_url, img_title, feed_type, user_id, last_fetched_at FROM feeds
WHERE $1 - last_fetched_at >= interval '1 hour'
`

func (q *Queries) GetFeedsToFetch(ctx context.Context, lastFetchedAt sql.NullTime) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsToFetch, lastFetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Descrip,
			&i.Link,
			&i.FeedLink,
			&i.UpdatedParsed,
			&i.PublishedParsed,
			&i.Lang,
			&i.ImgUrl,
			&i.ImgTitle,
			&i.FeedType,
			&i.UserID,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedFetched = `-- name: MarkFeedFetched :one
UPDATE feeds
SET last_fetched_at = $1,
updated_at = $1
WHERE id = $2
RETURNING id, created_at, updated_at, title, descrip, link, feed_link, updated_parsed, published_parsed, lang, img_url, img_title, feed_type, user_id, last_fetched_at
`

type MarkFeedFetchedParams struct {
	LastFetchedAt sql.NullTime
	ID            uuid.UUID
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetched, arg.LastFetchedAt, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Descrip,
		&i.Link,
		&i.FeedLink,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Lang,
		&i.ImgUrl,
		&i.ImgTitle,
		&i.FeedType,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const updateFeedByID = `-- name: UpdateFeedByID :exec
UPDATE feeds
SET 
    updated_at = $2,
    title = $3,
    descrip = $4,
    link = $5,
    feed_link = $6,
    updated_parsed = $7,
    published_parsed = $8,
    lang = $9,
    img_url = $10,
    img_title = $11,
    feed_type = $12,
    last_fetched_at = $13
WHERE id = $1
`

type UpdateFeedByIDParams struct {
	ID              uuid.UUID
	UpdatedAt       time.Time
	Title           string
	Descrip         string
	Link            string
	FeedLink        string
	UpdatedParsed   sql.NullTime
	PublishedParsed sql.NullTime
	Lang            string
	ImgUrl          string
	ImgTitle        string
	FeedType        string
	LastFetchedAt   sql.NullTime
}

func (q *Queries) UpdateFeedByID(ctx context.Context, arg UpdateFeedByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedByID,
		arg.ID,
		arg.UpdatedAt,
		arg.Title,
		arg.Descrip,
		arg.Link,
		arg.FeedLink,
		arg.UpdatedParsed,
		arg.PublishedParsed,
		arg.Lang,
		arg.ImgUrl,
		arg.ImgTitle,
		arg.FeedType,
		arg.LastFetchedAt,
	)
	return err
}
