// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addFeed = `-- name: AddFeed :one
INSERT INTO feeds (
    id, 
    created_at, 
    updated_at, 
    title, 
    descrip, 
    link,
    feed_link, 
    updated_parsed,
    published_parsed, 
    lang, 
    img_url, 
    img_title, 
    feed_type, 
    user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, created_at, updated_at, title, descrip, link, feed_link, updated_parsed, published_parsed, lang, img_url, img_title, feed_type, user_id, last_fetched_at
`

type AddFeedParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Descrip         string
	Link            string
	FeedLink        string
	UpdatedParsed   sql.NullTime
	PublishedParsed sql.NullTime
	Lang            string
	ImgUrl          string
	ImgTitle        string
	FeedType        string
	UserID          uuid.UUID
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, addFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Descrip,
		arg.Link,
		arg.FeedLink,
		arg.UpdatedParsed,
		arg.PublishedParsed,
		arg.Lang,
		arg.ImgUrl,
		arg.ImgTitle,
		arg.FeedType,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Descrip,
		&i.Link,
		&i.FeedLink,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Lang,
		&i.ImgUrl,
		&i.ImgTitle,
		&i.FeedType,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, created_at, updated_at, title, descrip, link, feed_link, updated_parsed, published_parsed, lang, img_url, img_title, feed_type, user_id, last_fetched_at FROM feeds
WHERE id = $1
`

func (q *Queries) GetFeedByID(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Descrip,
		&i.Link,
		&i.FeedLink,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Lang,
		&i.ImgUrl,
		&i.ImgTitle,
		&i.FeedType,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const markFeedFetched = `-- name: MarkFeedFetched :one
UPDATE feeds
SET last_fetched_at = $1,
updated_at = $1
WHERE id = $2
RETURNING id, created_at, updated_at, title, descrip, link, feed_link, updated_parsed, published_parsed, lang, img_url, img_title, feed_type, user_id, last_fetched_at
`

type MarkFeedFetchedParams struct {
	LastFetchedAt sql.NullTime
	ID            uuid.UUID
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetched, arg.LastFetchedAt, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Descrip,
		&i.Link,
		&i.FeedLink,
		&i.UpdatedParsed,
		&i.PublishedParsed,
		&i.Lang,
		&i.ImgUrl,
		&i.ImgTitle,
		&i.FeedType,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
