// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Descrip         string
	Link            string
	FeedLink        string
	UpdatedParsed   sql.NullTime
	PublishedParsed sql.NullTime
	Lang            string
	ImgUrl          string
	ImgTitle        string
	FeedType        string
	UserID          uuid.UUID
}

type FeedFollow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type FeedTopic struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FeedID    uuid.UUID
	TopicID   uuid.UUID
}

type Post struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Descrip         string
	PostLink        string
	UpdatedParsed   sql.NullTime
	PublishedParsed sql.NullTime
	ImgUrl          string
	ImgTitle        string
	Guid            string
	FeedID          uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type SavedPost struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	PostLink  string
}

type Topic struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	HashedPassword string
}

type UserSavedPost struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	SavedAt     time.Time
	UserID      uuid.UUID
	SavedPostID uuid.UUID
}
