// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPost = `-- name: AddPost :exec
INSERT INTO posts (
    id, 
    created_at, 
    updated_at, 
    title, 
    descrip, 
    post_link, 
    published_parsed, 
    img_url, 
    img_title, 
    guid, 
    feed_id
) VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type AddPostParams struct {
	ID              uuid.UUID
	Title           string
	Descrip         string
	PostLink        string
	PublishedParsed time.Time
	ImgUrl          string
	ImgTitle        string
	Guid            string
	FeedID          uuid.UUID
}

func (q *Queries) AddPost(ctx context.Context, arg AddPostParams) error {
	_, err := q.db.ExecContext(ctx, addPost,
		arg.ID,
		arg.Title,
		arg.Descrip,
		arg.PostLink,
		arg.PublishedParsed,
		arg.ImgUrl,
		arg.ImgTitle,
		arg.Guid,
		arg.FeedID,
	)
	return err
}
