// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPost = `-- name: AddPost :exec
INSERT INTO posts (
    id, 
    created_at, 
    updated_at, 
    title, 
    descrip, 
    post_link, 
    published_parsed, 
    img_url, 
    img_title, 
    guid, 
    feed_id
) VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type AddPostParams struct {
	ID              uuid.UUID
	Title           string
	Descrip         string
	PostLink        string
	PublishedParsed time.Time
	ImgUrl          string
	ImgTitle        string
	Guid            string
	FeedID          uuid.UUID
}

func (q *Queries) AddPost(ctx context.Context, arg AddPostParams) error {
	_, err := q.db.ExecContext(ctx, addPost,
		arg.ID,
		arg.Title,
		arg.Descrip,
		arg.PostLink,
		arg.PublishedParsed,
		arg.ImgUrl,
		arg.ImgTitle,
		arg.Guid,
		arg.FeedID,
	)
	return err
}

const getSubcribedPostsOfUser = `-- name: GetSubcribedPostsOfUser :many
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.descrip, posts.post_link, posts.published_parsed, posts.img_url, posts.img_title, posts.guid, posts.feed_id FROM posts
JOIN feed_follows ON posts.feed_id = feed_follows.feed_id
WHERE feed_follows.user_id = $1
ORDER BY posts.published_parsed DESC
`

func (q *Queries) GetSubcribedPostsOfUser(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getSubcribedPostsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Descrip,
			&i.PostLink,
			&i.PublishedParsed,
			&i.ImgUrl,
			&i.ImgTitle,
			&i.Guid,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
