// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: saved_posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addSavedPost = `-- name: AddSavedPost :one
INSERT INTO saved_posts (id, created_at, updated_at, title, post_link) 
VALUES (
    $1, NOW(), NOW(), $2, $3
)
RETURNING id, created_at, updated_at, title, post_link
`

type AddSavedPostParams struct {
	ID       uuid.UUID
	Title    string
	PostLink string
}

func (q *Queries) AddSavedPost(ctx context.Context, arg AddSavedPostParams) (SavedPost, error) {
	row := q.db.QueryRowContext(ctx, addSavedPost, arg.ID, arg.Title, arg.PostLink)
	var i SavedPost
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.PostLink,
	)
	return i, err
}

const getSavedPostByPostLink = `-- name: GetSavedPostByPostLink :one
SELECT id, created_at, updated_at, title, post_link FROM saved_posts
WHERE post_link = $1
`

func (q *Queries) GetSavedPostByPostLink(ctx context.Context, postLink string) (SavedPost, error) {
	row := q.db.QueryRowContext(ctx, getSavedPostByPostLink, postLink)
	var i SavedPost
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.PostLink,
	)
	return i, err
}
