// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name)
VALUES ("Hello")
RETURNING name
`

func (q *Queries) CreateUser(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var name sql.NullString
	err := row.Scan(&name)
	return name, err
}
