// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_saved_posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSaved = `-- name: CountSaved :one
SELECT COUNT(saved_post_id) FROM user_saved_posts
WHERE saved_post_id = $1
`

func (q *Queries) CountSaved(ctx context.Context, savedPostID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSaved, savedPostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unsavePost = `-- name: UnsavePost :exec
DELETE FROM user_saved_posts
WHERE user_id = $1 AND saved_post_id = $2
`

type UnsavePostParams struct {
	UserID      uuid.UUID
	SavedPostID uuid.UUID
}

func (q *Queries) UnsavePost(ctx context.Context, arg UnsavePostParams) error {
	_, err := q.db.ExecContext(ctx, unsavePost, arg.UserID, arg.SavedPostID)
	return err
}

const userSavePost = `-- name: UserSavePost :exec
INSERT INTO user_saved_posts (
    id, 
    created_at, 
    updated_at, 
    saved_at, 
    user_id, 
    saved_post_id
) VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    $4
)
`

type UserSavePostParams struct {
	ID          uuid.UUID
	SavedAt     time.Time
	UserID      uuid.UUID
	SavedPostID uuid.UUID
}

func (q *Queries) UserSavePost(ctx context.Context, arg UserSavePostParams) error {
	_, err := q.db.ExecContext(ctx, userSavePost,
		arg.ID,
		arg.SavedAt,
		arg.UserID,
		arg.SavedPostID,
	)
	return err
}
